SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema techshopperTables
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `techshopperTables` ;

-- -----------------------------------------------------
-- Schema techshopperTables
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `techshopperTables` DEFAULT CHARACTER SET utf8mb3 ;
USE `techshopperTables` ;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_USUARIOS` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_USUARIOS` (
  `ID_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `CONTRASENA` VARCHAR(45) NOT NULL,
  `ESTADO_CONEXION` ENUM('CONECTADO', 'DESCONECTADO', 'EN_ESPERA', 'RECONECTANDO', 'ERROR', 'LIMITADO') NOT NULL,
  `FECHA_REGISTRO` DATE NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `ROL` ENUM('CLIENTE', 'ADMINISTRADOR') NOT NULL,
  PRIMARY KEY (`ID_USUARIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_CLIENTES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_CLIENTES` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_CLIENTES` (
  `ID_CLIENTE` INT NOT NULL,
  `DIRECCION` VARCHAR(45) NOT NULL,
  `TELEFONO` VARCHAR(45) NULL DEFAULT NULL,
  `INFO_TARJETA_CREDITO` VARCHAR(45) NULL DEFAULT NULL,
  `BALANCE_CUENTA` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`),
  CONSTRAINT `FK_CLIENTES_USUARIOS`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `techshopperTables`.`TCS_USUARIOS` (`ID_USUARIO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_ADMINISTRADORES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_ADMINISTRADORES` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_ADMINISTRADORES` (
  `ID_ADMINISTRADOR` INT NOT NULL,
  `NIVEL_ACCESO` ENUM('BASICO', 'MEDIO', 'AVANZADO', 'SUPER') NOT NULL DEFAULT 'BASICO',
  `FECHA_ULTIMO_ACCESO` DATETIME NULL,
  PRIMARY KEY (`ID_ADMINISTRADOR`),
  CONSTRAINT `FK_ADMINISTRADORES_USUARIOS`
    FOREIGN KEY (`ID_ADMINISTRADOR`)
    REFERENCES `techshopperTables`.`TCS_USUARIOS` (`ID_USUARIO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_PRODUCTOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_PRODUCTOS` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_PRODUCTOS` (
  `ID_PRODUCTO` INT NOT NULL AUTO_INCREMENT,
  `PRECIO` FLOAT NOT NULL,
  `STOCK_DISPONIBLE` INT NOT NULL DEFAULT 0,
  `STOCK_RESERVADO` INT NOT NULL DEFAULT 0 COMMENT 'Productos reservados en carritos o pedidos no confirmados',
  `STOCK_MINIMO` INT NOT NULL DEFAULT 5 COMMENT 'Punto de reorden para alertas',
  `NOMBRE` VARCHAR(45) NOT NULL,
  `MARCA` VARCHAR(45) NOT NULL,
  `CATEGORIA` ENUM('LAPTOP', 'PC', 'MOUSE', 'MONITOR', 'TECLADO', 'AURICULARES', 'AUDIFONOS', 'MICROFONO', 'PARLANTES') NOT NULL,
  `DESCRIPCION` VARCHAR(45) NULL DEFAULT NULL,
  `URL_IMAGEN` VARCHAR(2000) NULL,
  `ID_USUARIO` INT NOT NULL COMMENT 'Usuario que creó/administra el producto',
  PRIMARY KEY (`ID_PRODUCTO`),
  INDEX `ID_USUARIO_idx` (`ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_PRODUCTOS_USUARIOS`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `techshopperTables`.`TCS_USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_MOVIMIENTOS_STOCK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_MOVIMIENTOS_STOCK` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_MOVIMIENTOS_STOCK` (
  `ID_MOVIMIENTO` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUCTO` INT NOT NULL,
  `TIPO` ENUM('ENTRADA', 'SALIDA') NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `FECHA` DATETIME NOT NULL,
  `ID_USUARIO` INT NULL COMMENT 'Usuario que realizó el movimiento',
  PRIMARY KEY (`ID_MOVIMIENTO`),
  INDEX `FK_MOVIMIENTO_PRODUCTO_idx` (`ID_PRODUCTO` ASC) VISIBLE,
  INDEX `FK_MOVIMIENTO_USUARIO_idx` (`ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_MOVIMIENTO_PRODUCTO`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `techshopperTables`.`TCS_PRODUCTOS` (`ID_PRODUCTO`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_MOVIMIENTO_USUARIO`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `techshopperTables`.`TCS_USUARIOS` (`ID_USUARIO`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_CARRITOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_CARRITOS` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_CARRITOS` (
  `ID_CARRITO` INT NOT NULL AUTO_INCREMENT,
  `PRECIO` FLOAT NOT NULL,
  `ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_CARRITO`),
  INDEX `ID_USUARIO_idx` (`ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_CARRITOS_USUARIOS`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `techshopperTables`.`TCS_USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_ITEMS_CARRITO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_ITEMS_CARRITO` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_ITEMS_CARRITO` (
  `ID_ITEM_CARRITO` INT NOT NULL AUTO_INCREMENT,
  `ID_CARRITO` INT NOT NULL,
  `ID_PRODUCTO` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `PRECIO_UNITARIO` FLOAT NOT NULL,
  `FECHA_REGISTRO` DATE NOT NULL,
  PRIMARY KEY (`ID_ITEM_CARRITO`),
  INDEX `ID_PRODUCTO_idx` (`ID_PRODUCTO` ASC) VISIBLE,
  INDEX `ID_CARRITO_idx` (`ID_CARRITO` ASC) VISIBLE,
  CONSTRAINT `FK_ITEMS_CARRITO_CARRITOS`
    FOREIGN KEY (`ID_CARRITO`)
    REFERENCES `techshopperTables`.`TCS_CARRITOS` (`ID_CARRITO`),
  CONSTRAINT `FK_ITEMS_CARRITO_PRODUCTOS`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `techshopperTables`.`TCS_PRODUCTOS` (`ID_PRODUCTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_LOCALIZACIONES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_LOCALIZACIONES` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_LOCALIZACIONES` (
  `ID_LOCALIZACION` INT NOT NULL AUTO_INCREMENT,
  `LATITUD` FLOAT NOT NULL,
  `LONGITUD` FLOAT NOT NULL,
  `DIRECCION` VARCHAR(45) NOT NULL,
  `ID_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_LOCALIZACION`),
  INDEX `ID_USUARIO_idx` (`ID_USUARIO` ASC) VISIBLE,
  CONSTRAINT `FK_LOCALIZACIONES_USUARIOS`
    FOREIGN KEY (`ID_USUARIO`)
    REFERENCES `techshopperTables`.`TCS_USUARIOS` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_ENVIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_ENVIOS` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_ENVIOS` (
  `ID_ENVIO` INT NOT NULL AUTO_INCREMENT,
  `FECHA_ENTREGA` DATE NOT NULL,
  `EMPRESA_COURIER` VARCHAR(45) NOT NULL,
  `PRECIO` FLOAT NOT NULL,
  `ID_LOCALIZACION` INT NOT NULL,
  PRIMARY KEY (`ID_ENVIO`),
  INDEX `ID_LOCALIZACION_idx` (`ID_LOCALIZACION` ASC) VISIBLE,
  CONSTRAINT `FK_ENVIOS_LOCALIZACIONES`
    FOREIGN KEY (`ID_LOCALIZACION`)
    REFERENCES `techshopperTables`.`TCS_LOCALIZACIONES` (`ID_LOCALIZACION`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_COMPRAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_COMPRAS` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_COMPRAS` (
  `ID_COMPRA` INT NOT NULL AUTO_INCREMENT,
  `PRECIO_TOTAL` FLOAT NOT NULL,
  `FECHA_COMPRA` DATETIME NOT NULL,  
  `ESTADO_COMPRA` ENUM('SIN_PAGAR', 'PAGADO', 'ENVIADO', 'RECIBIDO','CANCELADO') NOT NULL,
  `ID_ENVIO` INT NOT NULL,
  PRIMARY KEY (`ID_COMPRA`),
  INDEX `ID_ENVIO_idx` (`ID_ENVIO` ASC) VISIBLE,
  CONSTRAINT `FK_COMPRAS_ENVIOS`
    FOREIGN KEY (`ID_ENVIO`)
    REFERENCES `techshopperTables`.`TCS_ENVIOS` (`ID_ENVIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `techshopperTables`.`TCS_DETALLES_COMPRA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `techshopperTables`.`TCS_DETALLES_COMPRA` ;

CREATE TABLE IF NOT EXISTS `techshopperTables`.`TCS_DETALLES_COMPRA` (
  `ID_DETALLE_COMPRA` INT NOT NULL AUTO_INCREMENT,
  `ID_COMPRA` INT NOT NULL,
  `ID_PRODUCTO` INT NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `PRECIO_UNITARIO` FLOAT NOT NULL,
  `IGV` FLOAT NOT NULL,
  PRIMARY KEY (`ID_DETALLE_COMPRA`),
  INDEX `ID_COMPRA_idx` (`ID_COMPRA` ASC) VISIBLE,
  INDEX `ID_PRODUCTO_idx` (`ID_PRODUCTO` ASC) VISIBLE,
  CONSTRAINT `FK_DETALLES_COMPRA_COMPRAS`
    FOREIGN KEY (`ID_COMPRA`)
    REFERENCES `techshopperTables`.`TCS_COMPRAS` (`ID_COMPRA`),
  CONSTRAINT `FK_DETALLES_COMPRA_PRODUCTOS`
    FOREIGN KEY (`ID_PRODUCTO`)
    REFERENCES `techshopperTables`.`TCS_PRODUCTOS` (`ID_PRODUCTO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;